server:
  port: 8088
  #  避免中文乱码
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /universe-own

spring:
  datasource:
    url: jdbc:mysql://111.231.201.108:13306/universe?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 60000
      max-lifetime: 60000

  redis:
    database: 0
    host: 111.231.201.108
    #    host: 127.0.0.1
    port: 16379
    password: root
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 5
        min-idle: 1
    timeout: 10s
dubbo:
  application:
    name: universe-owner-api
  registry:
    address: nacos://192.168.118.1:8848
  protocol:
    name: dubbo
    port: 20880
nacos:
  discovery:
    server-addr: 192.168.118.1:8848